### ISSUE TITLE
support for # 19333129212931623 ? ??

### ISSUE THREAD

**Issue by 0xF48** [avinassh/gg-flip#12]
Hi im AmIR. I really appreicate your tool GAS !  its a good tool and i use it in my java site facemagazine , i have experience with this tool for > 2 years!! can you pls add support for # 19333129212931623 ? ??

**Comment by avinassh** [comment]
hey, the number overflows because of JS limitation as max int is `9007199254740991`

https://stackoverflow.com/questions/26380364/why-is-number-max-safe-integer-9-007-199-254-740-991-and-not-9-007-199-254-740-9
