### ISSUE TITLE
Final Lib Size?

### ISSUE THREAD

**Issue by ThoriumQuasimodem** [avinassh/gg-flip#7]
```The final lib size is few GBs```
I hope you mean "MBs"!

**Comment by RobotCaleb** [comment]
...

**Comment by kalafut** [comment]
You're actually looking at around 1.25 EB, or $28M/month in S3 (storage only).  Not bad.

**Comment by avinassh** [comment]
Nope, it is few GBs. I am currently looking for ways to optimize this

**Comment by jwilk** [comment]
If I did the maths right, the size of `lib.js` is 1328621045257222335, so slightly over an exabyte.

So you are both right: it's a few megabytes, or a few gigabytes, but for very big values of *few*.

**Comment by ThoriumQuasimodem** [comment]
Aye!  Never encountered a GB-sized lib, let alone an exabyte-sized lib, figured it was a typo without running any numbers at all.  Apologies for the noise!
